### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by federicomarini**
Dario's surname spelled fully :)

While at it: Do you want to update the current citation in the README? This still points only to the preprint.

Fede

### CODE REVIEW

**Review by drighelli — APPROVED** [review]

**Comment by lmweber** [comment]
Thanks for this @federicomarini . Yes, definitely good to update this!

I also updated the year and volume/issue/page/etc in the rest of the citation, and the second link to the paper near the top of the readme. While we are at it I also cleaned up the installation instructions on the rest of the readme page, which were referring to a much older version, so I think this wasn't needed any more. (The info about those changes is also recorded in `NEWS`.) @drighelli does this look ok?

**Review by lmweber — APPROVED** [review]

**Review by drighelli — APPROVED** [review]

**Comment by drighelli** [comment]
Everything looks good! 
Thanks! 

How are we acting for the merge? Are we merging on the main?

**Comment by lmweber** [comment]
Great, thanks. Yes, I'll add version bump and merge and push to both github/origin and bioc/upstream now.

**Comment by lmweber** [comment]
Done

**Comment by drighelli** [comment]
Thanks, as usual, Lukas!

**Pull request merged**
