### PR TITLE
Massive PR restructuring an S4 class for ST data

### PR DESCRIPTION
**Pull request by HelenaLC**
Dear all, 

I could work another eternity on this, but I believe things have reached a state where it is of interest to share the current state and crowd-source ideas. Below a "few" comments, many of which come out of a recent discussion with Aaron:

**Design choices:**

* I had a feeling that there is no real necessity to add a new slot per se, as the SCE already provides all the slots necessary to store the data we have. 
* Thus, all spatial and image-related data are stored in the `colData` and `int_metadata`, respectively. 
* As a result, validity checks are used to assure the correctness of these fields, while the class definition itself is fairly skinny - it simply contains the SCE class. 
* Along those lines, I think that having a `SpatialExperiment` with image-related data and spatial coordinates is sufficient (when kept fairly general), and there needn't be a class specific to Visium or other spot-based data. However, a subclass for single-molecule resolution certainly makes sense.
* I think many agree the data is complex enough to justify a constructor. My guess is that anyone working with this data has already written a wrapper to load & reformat the data in one way or another. 
* Thus, I'd argue the `xExperiment()`-way of initialising the object should be limited to developers, and it would be preferable to provide relevant constructors a la `DropletUtils`, e.g. `read10xVisium()`.

**Disclaimers:**

* All unit-tests are broken. I am happy to write of them, but thought this only makes sense to do once we agree on a final class structure. 
* It might be worth thinking about which functionality we want to provide (besides class definition) in this package vs. in a separate one (e.g. something like `STUtils` or `SpatialUtils`). I think both designs have their (dis)advantages, but would argue that the data is too complex to provide a class definition only and require another package to handle the data. I'm thus personally in favour for the all-in-one option, provided we can keep the number of dependencies as low as possible.
* The `vignettes/10xVisium.Rmd` is not intended to be a vignette, but rather demonstrate how things (could) work. It includes a rather chunky visualisation wrapper that is adapted from what I've been using previously; but is for demonstration purposes only, not to be included in the package.
* Finally, I tried to include preliminary documentation everywhere, but this surely needs to be extended and possibly restructured.

**Todo:**

* Lots of things. But mainly, I think regardless of how we restructure the class(es), we should provide a way of supporting backward-compatibility.
* Aaron suggested adding a version flag in the `int_metadata`; if this is < x, we call an `.update()` function that converts an old- to new-version object. I think this would be straightforward to write, and hopefully all the `VisiumExperiment` stuff will still work then.

### CODE REVIEW

**Comment by lmweber** [comment]
Hi @HelenaLC , thanks for all this. I have had a look through the vignette, and I think it looks great. I have a few questions below:

- What exactly does the `int_metadata` slot do? I understand that `int_colData` makes sure columns are lined up correctly, and then users only interact with it via getters / setters. Is `int_metadata` used mainly for passing validity checks?

- For the part about `colData` column name replacement: do I understand this correctly, i.e. the column names `sample_id`, `in_tissue`, and `xy_coords` are protected, but users can still add other arbitrary columns later, e.g. cluster labels? As long as it is still possible to add additional columns, I think this is fine.

- For the `xy_coords`, this is now stored as a matrix within the `colData`, instead of simply additional columns (`x_coord`, `y_coord`, possibly also `z_coord`, `t_coord`, etc). This seems quite complex - was there a reason for this, e.g. makes things easier for the validity checks and column name protection?

- And so you are arguing that we don't really need the `SpatialSpotExperiment` and `SpatialMoleculeExperiment` subclasses at all, with Visium objects simply being part of the main `SpatialExperiment` class? My first reaction here is that this could cause problems / conflicts later, e.g. if there are Visium-specific structures that don't make sense to have in seqFISH objects. This would be avoided if we have sub-classes for each. But maybe you are right, and there is nothing in Visium objects that conflicts with seqFISH. I'll think about this some more.

Thanks again! I'll also try installing it and reshaping some of my objects, to see if I think of anything else.

**Comment by lmweber** [comment]
On the question of whether to have a separate `STUtils` (or similar) package with additional functions:

- I agree it is probably better to have this all within one package, i.e. putting `read10xVisium()` and other similar functions directly within the `SpatialExperiment` package. Otherwise the second package would be tiny, with just this one function for now. I'm not sure what else we would have in there right now.

However visualization functions definitely belong in a separate package, as we discussed. I'll set this up so we can start collecting them there.

**Comment by lmweber** [comment]
And I think your point that we don't really need an `imgData` (or `spatialCoords`) slot makes sense, since everything fits within either `colData` or `metadata`. From the user perspective, this should be fine as long as we have all the getter functions e.g. `imgData()`.

**Comment by LTLA** [comment]
@HelenaLC: Suggest moving the data out to more appropriate locations, e.g., the 10X data can go into **DropletTestFiles**. The SeqFISH stuff should really find its home in another package - suggest @shazanfar get onto prepping this.

@drighelli Future note: strongly recommend to squash the changes rather than to do a straight merge; it looks like the `.git` directory has accumulated 170 MB of crud, compared to the current `master` with 1.5 MB.

@lmweber `int_metadata` is just for miscellaneous internal stuff that you don't want users to see, e.g., the package version. Have a look at how SCE's `updateObject` extracts this information to figure out how to update old objects.

The choice between storing coordinates as a matrix or as separate columns is an interesting one. From a data structure perspective, a matrix is preferable as it allows further dimensions to be easily added without requiring hard-coding of the column names. From a downstream usage perspective, it's a coin toss; **ggplot2** and other `data.frame`-centric procedures (e.g., saving arbitrary SE content into a HDF5 file) would need columns but most serious analytical functions would prefer matrices (e.g., to compute distances or what-have-you). Having thought about it a bit, it may be best to store it as columns but to provide a getter that extracts it into a matrix without requiring the downstream developer to remember the hard-coded column names. The getter can also handle the search for a `z_coords` that may or may not be present, depending on the data.

The only difference between a hypothetical `SpatialSpotExperiment` and `SpatialMoleculeExperiment` is the expectations of the `colData()` and `assay()` fields that would be available. The latter would have additional fields for the cell vertices in the `colData()`, and an additional assay (I call these BumpyMatrices, implementation to be released soon) containing the per-cell/gene coordinates of all transcript molecules. It may be sufficient to have these as informal expectations, in much the same way that an SE is not obligated to have a count matrix for RNA-seq data - but it should, if you want to do any serious analysis on it.

**Comment by drisso** [comment]
Hey @LTLA,

can you tell us a bit more about the upcoming `BumpyMatrices` class? And how do you envision it used in the context of seqFISH?

The main conceptual barrier for me to have only one container for Visium-type data and seqFISH-type data is that in the latter, the unit is not the cell but the transcript (i.e., you have a transcript coordinate rather than a cell coordinate -- at least in the "raw" data). It's totally fair if your response is just "wait and see" but I would love some intuition on how a new data class may help us with this issue.

My two cents on the coordinates: I agree with Aaron that especially if we want to have easy interoperability with ggplot2 it is better to store them as columns. I really like the idea of having a getter that extracts them as a matrix/array.

I will have a more thorough look at the PR and come back with comments if I have more.

**Comment by drighelli** [comment]
Hi everyone, 

First thing, thanks @HelenaLC for doing this, it's a lot of work made in a really short time.

I went through the PR (mainly the code) and I noticed (and already discussed with @HelenaLC) some points.

- I like the idea to have a single class for managing the spatial data. It's easier to maintain and it can be specified in subclasses in the future if needed.  It's also simpler to create coercion methods for other tools classes.
- I like how the images and multiple samples are handled into the class.
- About the spatial coordinates (SC): as implemented in the PR, they go into the `colData` structure and they don't have accessors. But I don't totally agree with these choices. They have multiple different implications imho.
    - We need accessors for easy get/set SC 
        - for better code maintenance 
        - for not giving the user direct access to the attributes
        - we can also provide SC accessors overloading (the "same method" can be used to retrieve the original data as it is, in matrix form or whatever we need for the analysis.)
 - Storing the SC into the `colData` 
    - could be **good** so the user can retrieve them in a direct manner (using `$` or their `colnames`) and combine them in an easier way with other data to do plots or analysis.
    - could be **bad** because the user should not have direct access to fixed attributes and (less important) the `colData` method become unnecessarily difficult to maintain.
    - Maybe we can **discuss** storing the SC into the `int_colData` and accessing them with the needed accessors. Imho it's cleaner and less complicated.

For the constructor(s) we all agreed to have functions into the `SpatialExperiment` for loading well knows files formats (10x_visium and seqFISH long format files). I'd also suggest applying the overloading for the constructors, in such a way the user can choose to build the object starting from already loaded raw data from memory, or by loading a file/filepath.

@LTLA thanks for the point! I need to understand how to squash instead of merge, but I'll message you in case I don't figure it out! :D

@drisso as you and @LTLA  mentioned, once we have accessors we can transform the data into other classes as needed. 

Thanks @lmweber for creating the spatial visualization repository, it's good to know how to put/take all the functions for that! ^^

**Comment by drighelli** [comment]
Hi guys,

I was thinking to start to merge/squash the new class into the package and to work on some issues, such as the accessors because I have a workshop on spatial data with the SpatialExperiment class during the EuroBioc2020 conference.

Then at the conference at BoF, we can discuss further improvements for the class.

Anyway, I'll try to implement additional feedbacks in the next days!

Dario

**Comment by lmweber** [comment]
Minor point: for the column names of the x/y/z coordinates, I would use `x_coord`, `y_coord`, etc (i.e. singular, not plural i.e. `x_coords`, `y_coords`), since this is more consistent with other column names which are usually also singular (`sample_id`, `gene_id`, etc).

**Comment by LTLA** [comment]
@drisso See slack.

Thinking about it some more, it doesn't really matter that the x/y coordinates are columns, as you end up having to scale them by the scaling factor anyway. So either way, some extra work would be required before **ggplot2** could be used. But having them as columns does make the data structure easier to interpret, and given that there's only a few options (`x_coord`, `y_coord`, and maybe `z_coord`) I don't think it's a big deal; it's not like we're, e.g., flooding the `colData` with PCs 1 through 50.

@drighelli:

- Is there a reason for not allowing people to see and modify these fixed attributes? If you have a look at what is currently in the SCE's `int_colData`, you will see very complex objects - nested matrices and SEBC objects within DFs. These are hidden to avoid confusing users with the implementation details; and at minimal cost, because users wouldn't know what to do with them anyway. In contrast, the spatial information is routine column data, with the most complex being the coordinate matrix.
- Separating the in-memory constructor from the file loading function seems to be the most appropriate approach given that there is no reason that future uses of the class will be limited to 10X-formatted data. If you stick them together in the same function, people will also expect the constructor to handle every new type of spatial data. For such complex classes, the constructor function is intended to be called by other functions (like `read10xVisium`) to avoid the need for a raw `new()` call.

**Comment by HelenaLC** [comment]
Sorry all- I’ve been traveling and wasn’t able to have a look at all this yet... for what it’s worth: I strongly vote for keeping spatial coordinates in a single column as a matrix (be it in the col or int_colData). For a simple reason: 
You would never(!) just need, say, the x_coord. Meanwhile, there’s bunch of spatstats that could be run on the unscaled matrix of coordinates. So for me, that’s 100% reason enough to NOT separate them. Plus, it looks much better to me than having x_coord y_coord...

**Comment by HelenaLC** [comment]
Also @drighelli ... regardless of where we move stuff- the colData replacement override will have to stay anyways. And we’d need another int_colData replacement override. So... I don’t really see the point with hiding things from the user just because they “are fixed”. If people want to break their object, they can also do that in the int_colData. So I’d rather give easy access than trying to hide stuff when that ultimately doesn’t really protect against breakage. 
With that logic, ALL metadata should go into the int_ slots because what if someone computes % mitochondrial genes and then they overwrite it?! Well, then that’s their fault.

**Comment by drighelli** [comment]
@LTLA @HelenaLC  
- yes we have to keep separated the constructor from the loading data functions! 
- for the SC we can keep them into the colData, but I still think to leave them as columns, providing an additional method for having them as matrix.

Dario

**Comment by drisso** [comment]
I also vote to keep the coordinates in the visible colData as columns, since one of the first things that I want to do in these data is simply plot the coordinates of the cells colored by e.g., cluster labels. Being able to do just this is what makes it valuable IMO to have them as columns:

```{r}
colData(spe) %>%
    ggplot(aes(x_coord, y_coord), col=cluster_lab) +
    geom_point()
```

**Comment by HelenaLC** [comment]
Yes actually, I agree. Most of the time we prob. don’t need the image, in which case no scaling is necessary, and having them as columns is best. So I change my mind to having them as columns (not a matrix) in the colData (not int_) 👍

**Comment by lmweber** [comment]
Just checking - is the plan still to also have a `spatialCoords()` getter function? I think this would be useful. I'm somewhat less sure about a setter.

**Comment by lmweber** [comment]
Also did we make a decision regarding constructor functions?

I think in most cases, we will construct objects with the platform-specific functions e.g. `read10xVisium()`.

However a basic constructor function `SpatialExperiment()` would probably also be useful for more general cases, e.g. if someone is trying something out for a new technology. So we should probably still include this too.

**Comment by drighelli** [comment]
Hi @lmweber,

I'm already working on the `spatialCoords`, we'll have a getter/setter called `xyzData` (because we have the coordinates stored into the `colData` as `x_coord`, `y_coord` and `z_coord` (this can be null).  

We have a general constructor already, I'm still looking into the code for the `imgData` loading, because at the moment the constructor takes `xyzData`, `imgData`, `sample_id`, `inTissue`,
Where `imgData` is a `DataFrame` within all the images information.

**Comment by HelenaLC** [comment]
Agreed- yes to both. I already had a basic constructor, which will need adapting; unfortunately I didn’t understand the seqFISH data details to write a constructor for that. But I think the visium one is super useful for sure and safes lots of work.

**Comment by drighelli** [comment]
Yes @HelenaLC indeed you made a lot of work, I'm still looking into all your code :D

The only issue is that (IMHO) we need a general constructor for each data type and then build methods/functions for loading the data into the proper way into the class.
(I think that it's the same thing that also @LTLA was saying a few comments ago)

**Comment by lmweber** [comment]
Great - I think maybe `spatialCoords()` could be a better name for the getter/setter than `xyzData()` though, since it is more general (it doesn't assume we have `z`; and leaves open the possibility of adding additional columns in the future, e.g. `t`).

**Comment by drighelli** [comment]
I stuck on the `xyz` because the class was rightly already thought with the possibility of loading three dimensions 
(and also because I liked the idea of having all the methods in a 3-letterData format >.<)

Btw you're right, we need a more general name for the method... We'll come up with something ^^

**Comment by lmweber** [comment]
Yeah not super important - but generally I think simple is best, so people know what it is without looking at help files. So for me, `spatialCoords` would work nicely.

**Comment by drighelli** [comment]
Maybe you're right, it'd be easier also for the already implemented methods in other packages.

**Pull request merged**
