### PR TITLE
Adding spatial flags to colData

### PR DESCRIPTION
**Pull request by drighelli**
Fixing issue https://github.com/drighelli/SpatialExperiment/issues/69

### CODE REVIEW

**Review by lmweber — APPROVED** [review]
This looks very good, thank you! I have added some minor updates in the commits above, as discussed on Slack.

**Review by drighelli — COMMENTED** [review]
all revised except for the vignette, I suppose there are still changes to do

**Comment by drighelli** [comment]
@HelenaLC check are still failing on the vignette:
https://github.com/drighelli/SpatialExperiment/pull/70/checks?check_run_id=3168562104#step:14:28

**Comment by HelenaLC** [comment]
My bad. Forgot adding `library(SpatialExperiment)` upon removing the installation section...

**Pull request merged**
