### PR TITLE
Implemented the SpatialImage class hierarchy with caching, closes #24.

### LINKED ISSUE #24: ?SpatialImage should document the preferred sources
I can't remember what @HelenaLC and I discussed, but there was an order to what was checked to get the image. Maybe it was:

- The loaded grob, if available
- The file path
- The URL? Can't remember.

Roughly in order of how much effort it would take to load it into the R session.

Come to think of it, what was the use case for the URL again? Seems like we'd always be caching the image locally anyway.

### PR DESCRIPTION
**Pull request by LTLA**
One could argue that we don't even need the `LoadedSpatialImage` if we just use `raster` objects directly. However, `raster` objects aren't really that common, and it's just easier to say "must be a `SpatialImage` subclass" in the `imgData` slot.

Tests are left as an exercise for interested parties.

### CODE REVIEW

**Comment by drighelli** [comment]
Thanks @LTLA !!

Can we ask you to move this PR from the `master` branch to the newly updated `devel` branch?

So, @HelenaLC can work better on it...

Thanks!

**Comment by LTLA** [comment]
Tests have been added. You should incorporate the new class into the rest of the SpE. The most important points are:

- `SpatialImage()` will attempt to auto-detect the most appropriate subclass based on its input arguments, much like `List()`.
- There is no need for separate `nrow` and `ncol` columns, you can just get this same information from `dim(<SpatialImage>)`. The former is not ideal as it increases the risk of the separate dims getting out of sync with the stored image.

**Comment by drighelli** [comment]
Thanks @LTLA !

@HelenaLC is on this :)

**Comment by HelenaLC** [comment]
Q for @LTLA - working thru this now... I guess `unloadImg()` is gone then? Once the `SpatialImage` (SPI) is loaded, we lose the original source (path/URL). So `loadImg()` will coerce from `Remote/FileSpatialImage` to `Loaded`, but `unloadImg()` won' work anymore... Or am I missing something?

**Comment by LTLA** [comment]
Yes, that's correct. The whole idea with the cache is that it is no longer actually necessary to explicitly load images, because they're already loaded into memory by default. (Up to a 4 GB limit.) So it all happens under the hood, rather than requiring the user to actively think, "is this image loaded or not?". The real equivalent to `unloadImg()` is to flush the cache and garbage collect; you could convert `.flush_cache()` into an exported function + `gc()` if you like.

**Comment by HelenaLC** [comment]
Did an update on the `devel` branch to consolidate the new with the old... However, I keep getting an error in the example of `imgData-methods.R` ... any ideas?

```
example(read10xVisium)

url <- "https://i.redd.it/3pw5uah7xo041.jpg"

ve <- addImg(ve,
  sample_id = "section1",
  image_id = "pomeranian",
  imageSource = url,
  scaleFactor = NA_real_,
  load = FALSE)

img <- imgRaster(ve,
  sample_id = "section1",
  image_id = "pomeranian")
  
> Error in BiocFileCache::bfcrpath(cache, URL) : 
  not all 'rnames' found or unique.
In addition: Warning message:
In FUN(X[[i]], ...) : 'rnames' exact pattern
  'https://i.redd.it/3pw5uah7xo041.jpg'
  is not unique; use 'bfcquery()' to see matches.
```

**Pull request merged**
