### PR TITLE
SpE new vignette

### PR DESCRIPTION
**Pull request by drighelli**
defining the new vignette

Waiting for feedback on missing sections.

The subset is commented based on https://github.com/drighelli/SpatialExperiment/issues/56

### CODE REVIEW

**Comment by lmweber** [comment]
I added a few minor updates in the commit above:

- typos / grammar / wording updates
- added a small example showing the `spatialData(., spatialCoords=TRUE)` option

I also noticed two additional things:

- we say the default sample ID is `sample_01`, but in the constructor arguments it is `sample1`. Should we change the default in the constructor to `sample_01` or `sample01`?
- should we also delete the files for the previous vignettes, since these are no longer needed?

**Review by lmweber — APPROVED** [review]

**Comment by HelenaLC** [comment]
Re default sample IDs - where does it say _01? I remember changing from sample01 to sample1 in the SPE constructor to be consistent with `read10xVisium` (because one had use 01, the other 1). I think sample1,2,... is simplest, but it's a matter of taste. Open to 0x format, but I think I definitely don't like the extra underscore...

**Comment by drighelli** [comment]
I also agree on changing from sample1 to sample01 also because in some systems in case you have 1:10 and then sort the 10 comes before the 2.

**Comment by drighelli** [comment]
Is it ok if I push the [subset fix](https://github.com/drighelli/SpatialExperiment/issues/56) along with the vignette improvements?

**Comment by HelenaLC** [comment]
Since Lukas approved it, our guidelines say: Yes, you may merge ;) I haven't had time to look at it yet, but can have a look later... Just went through the other PR as well.

**Comment by drighelli** [comment]
No worries and no rush, I'm going now to put the sections you suggested me yesterday! ;)
We can always merge after/during our today meeting :)

**Comment by drighelli** [comment]
Ok I made a new commit with the https://github.com/drighelli/SpatialExperiment/issues/56 fix and a sample_id(s) error chunk in the vignette.

@lmweber About the older vignettes, I didn't delete them yet to avoid conflicts.

I thought that we can delete them once we merged all the PRs together...

**Pull request merged**
