### PR TITLE
SPE schematic in vignette and other small updates

### PR DESCRIPTION
**Pull request by lmweber**
Adding the SPE schematic to the vignette, as discussed on Slack.

I also made a few other small updates, including:
- replaced wording in first paragraph of vignette to match wording in DESCRIPTION and readme
- fixed some indenting
- added me as an author on the vignette
- some other small wording and formatting updates in the vignette

### CODE REVIEW

**Review by drighelli — COMMENTED** [review]
I'm asking because I don't know, are you sure that's the right place for the image vignette?

**Comment by lmweber** [comment]
Ah you mean where to save the image file?

Yes, I did some googling and I think saving it in the `vignettes/` directory next to the `.Rmd` file is the correct place.

**Review by drighelli — APPROVED** [review]

**Comment by HelenaLC** [comment]
If we’d also like to include it in the README it could go in inst/

**Comment by lmweber** [comment]
Ah yes, good idea to add it to the readme too. I think this works from either location though. If it is in `vignettes/` then we can add it with ``, or alternatively from `inst/` with ``.

I somewhat prefer having it in `vignettes/` because this makes the code in the vignette simpler, i.e. can include it without the relative path: `knitr::include_graphics("SPE.png")` vs `knitr::include_graphics("../inst/SPE.png")`.

Not a strong preference though so let me know what you think. Thanks!

**Comment by HelenaLC** [comment]
I see. Sure, if you have access either way put it in vignettes/ 👍

**Comment by lmweber** [comment]
I added the SPE image to the readme in the branch, and also updated the readme installation instructions to reflect versions 1.5.2 and 1.5.3. If this passes and you are happy with it, then I think we can merge.

**Comment by drighelli** [comment]
You can merge for me! Nice work and thanks!

**Comment by lmweber** [comment]
Something is failing in the GitHub Actions build today for Mac OS, but it looks like it is a problem with the GHA builders (it says something about homebrew installation in the logs), so nothing wrong with our code and we can probably safely ignore / restart the GHA build again tomorrow.

**Comment by lmweber** [comment]
Ah it is due to the release of R 4.1.3 today, which is now available in source but not in binaries yet (so GHA couldn't find the R 4.1.3 binary for Mac). So this should resolve in a day or two.

**Pull request merged**
