### PR TITLE
Spatial data relocation

### PR DESCRIPTION
**Pull request by HelenaLC**

### CODE REVIEW

**Review by drighelli — APPROVED** [review]

**Comment by drighelli** [comment]
Thanks, it seems fine to me!

**Comment by lmweber** [comment]
Thanks @HelenaLC , the implementation looks good. However I wanted to check about the design and documentation.

So now we have `spatialData` simply as a subset of `colData`, which means users can easily store or retrieve spatial data columns in `colData` (without using `spatialData`) if they prefer. This largely solves our issue of users being confused about what goes in `spatialData` vs. `colData`, since they can just use `colData` if they prefer.

However in the examples (e.g. `?SpatialExperiment`) and in the show method for SPE objects we are still using/showing `spatialData`. Should we also remove it here? And then only leave `spatialData` for backward compatibility (and explain this in the documentation)? Otherwise I worry that users will see `spatialData` here and then we still have the same confusion issue we had previously. What do you think?

**Comment by lmweber** [comment]
Ok, no worries, thanks. Yes I was just thinking from perspective of a user looking at their object, so then right now they would see `spatialData` or `spatialDataNames` and think they need to provide something. On the other hand maybe I am overthinking it. I'll look at the docs/examples and maybe we can clarify it there somehow.

**Comment by HelenaLC** [comment]
@lmweber any update on this?

**Comment by lmweber** [comment]
Hey, sorry for delays over the break.

Ok, I have looked at this some more, and I think yes the implementation is great and ensures backward compatibility, but for new users it would be best if we say in the documentation that `spatialData` and `spatialDataNames` are deprecated and we recommend using `colData` instead. This removes the ambiguity issues that our users were concerned about.

So I am thinking something like this (from my cloned branch where I am testing it out): https://github.com/drighelli/SpatialExperiment/compare/spatialData_relocation...lmweber:spatialData_relocation

Here I have removed `spatialData/Names` from the show method, and added some wording mentioning that it is deprecated in the help file. However the functionality is still there for backward compatibility.

What do you think? If you are happy with this, I can go through and update the rest of the docs / examples and add it here in the pull request.

**Comment by HelenaLC** [comment]
Yes, agreed & the changes I see all look reasonable. As I said, I think I had forgotten about / misunderstood this (the deprecation part). But agree that we should "hide" it as far as possible and note the deprecation in the documentation. For consistency, though, I think we also want to give a message when `spatialData` and `spatialDataNames` are called, perhaps even when these are passed in the constructor?

**Comment by lmweber** [comment]
Ok cool, thanks for looking at it. Yes, a message when `spatialData/Names` are called and/or passed in the constructor is a good idea.

I'll make some more updates and check the docs for consistency, then add the commits here in the pull request.

**Comment by lmweber** [comment]
Ok how about the following: https://github.com/lmweber/SpatialExperiment/commit/0ac63638398b0c468016a63d115f89afd7cc4038

Basically just a utils function that generates a message and then calling this inside the constructor and/or replacement methods.

(Although right now this is outputting multiple messages, probably because the constructor also calls the replacement methods internally. Maybe there is a way to clean this up and output only a single copy of the message.)

**Comment by lmweber** [comment]
Fixed the duplicated messages in an additional commit in my clone. I'll work on updating examples and docs next.

**Comment by lmweber** [comment]
Ok I have updated the rest now. Could you please have a look to check? Thank you!

These additional changes do the following:
- added a message if user uses `spatialData/Names`
- changed order of arguments in constructor so `spatialData/Names `is at the end in the list of arguments in the help file (this is only cosmetic, but I think it makes it easier for new users so the deprecated arguments aren't listed first)
- updated validity check for `spatialData` so it is only checked if `spatialData` is actually used
- updated all examples and docs so that `spatialData/Names` are no longer used in the default examples
- updated vignette similarly
- added some unit tests
- NEWS and version bump

**Comment by lmweber** [comment]
(The checks are fine locally with `devtools::check()`. Looks like something is wrong with GitHub Actions right now in the R installation step.)

**Review by lmweber — APPROVED** [review]

**Pull request merged**
