### PR TITLE
code-style revision

### PR DESCRIPTION
**Pull request by HelenaLC**
* Major code-style revision for consistency overall and with Bioc guidelines, including
  * indents of 4 spaces
  * keeping to a 80-character limit
  * spaces around logical operators (e.g. `!=`, `==`) but not argument `=`s
  * accession with accessors (and not `@`)
  * in-line `{` for function definitions, if-else statements etc. 
  * ...

* Minor fix in `spatialData()` and `test_spatialData-method.R` to pass R CMD check as unit-tests failed do to previous changes. 
* Re-ordering of some roxygen documentation to be consistent in the order of headings across files.

### CODE REVIEW

**Comment by lmweber** [comment]
The formatting changes look good to me.

I also tried running `BiocCheck()` and `devtools::check()`, and it is still giving some issues, although maybe these are better addressed in additional pull requests after this one:

- large file sizes in git history. I would be happy to volunteer to try updating this using BFG Repo-Cleaner. I think there was a discussion about this in Bioc Slack recently, since it requires overwriting old commit hashes. Right now the repo directory is quite large (56M), so I think this is worth trying to fix.

- some recommended additional `biocViews`

- something about `LazyData` in `DESCRIPTION`. Not sure I understand this one.

- `Unexported object imported by a ':::' call: ‘S4Vectors:::disableValidity’`

- some of the tests are failing, since `spatialData()` now returns a `DataFrame`

**Review by lmweber — APPROVED** [review]

**Comment by drighelli** [comment]
I had a fast look into the code...

The styling looks fine, but it still fails some checks on Windows and the `inst/NEWS` file is not updated with the latest changes.

Could you please account for these?

**Comment by lmweber** [comment]
I just had a look at the check outcomes - I thought the failed checks were due to the issue of `spatialData()` now returning a `DataFrame` instead of `data.frame`, but looks like it is something else:

```
SpatialImage in-memory caching works as expected --
names(cache$cached) not identical to c(LETTERS[1:3]
```

Do you know what is causing this? If it is part of the other class design issues we are working on, we can also leave it for later.

**Comment by HelenaLC** [comment]
I don't know what's causing this, I didn't get this when running checks locally. But I remember I previously had another cache-related issue, which I mentioned in PR #34, which we never fixed because we wanted the SPI update to be available asap...

**Comment by HelenaLC** [comment]
I did another push to i) bump the version to 1.1.5 (current Bioc devel is 1.1.434) and ii) update the NEWS file to include recent changes (and some added line-breaks for readability)

**Review by drighelli — APPROVED** [review]

**Pull request merged**
